use_frameworks!

platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'MoyaResponseHandlerPlugin_Example' do
  pod 'MoyaResponseHandlerPlugin', :path => '../'

  target 'MoyaResponseHandlerPlugin_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
