use_frameworks!

platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Lucid_Example' do
  pod 'Lucid/RxSwift', :path => '../'

  target 'Lucid_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
